import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { AppProvider } from "@widgets";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang={"ru"} style={inter.style} className={"scrollbar-hide"}>
      <body className={`antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}